apiVersion: 1
datasources:
- name: Alertmanager
  uid: alertmanager
  type: alertmanager
  url: http://localhost:9093
  access: proxy
  orgId: 1
  jsonData:
    implementation: prometheus
    handleGrafanaManagedAlerts: true
  editable: true
