version: '3.6'

services:
  web:
    build: .
    image: 81318131/fastapi_gpt
    container_name: fastapi_gpt
    command: fastapi run app/main.py --port 80
    volumes:
      - './app:/code/app'
    environment:
      OPENAI_API_KEY: ${KEY:-}
      TEST: ${TEST:-}
    ports:
      - "80:80"
