apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "<.Release.Name>.fullname" . }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "<.Release.Name>.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "<.Release.Name>.name" . }}
    spec:
      containers:
        - name: {{ include "<.Release.Name>.name" . }}
          image: {{ .Values.web.image }}
          ports:
            - containerPort: {{ .Values.web.service.targetPort }}
          env:
            - name: ENV1
              value: Hi
