apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "<.Release.Name>.fullname" . }}
spec:
  rules:
    - host: {{ .Values.web.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "<.Release.Name>.fullname" . }}
                port:
                  number: 80
