apiVersion: v1
kind: Service
metadata:
  name: {{ include "<.Release.Name>.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.web.service.targetPort }}
  selector:
    app: {{ include "<.Release.Name>.name" . }}
