apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: web-service
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image }}
          ports:
            - containerPort: {{ .Values.web.targetPort }}
          env:
            - name: {{ .Values.web.env[0].name }}
              value: {{ .Values.web.env[0].value }}
      volumeClaimTemplates:
        - metadata:
            name: web-pvc
          spec:
            accessModes:
              - {{ .Values.web.persistence.accessModes[0] }}
            resources:
              requests:
                storage: {{ .Values.web.persistence.size }}
