---
- name: Install CA certificates to ensure HTTPS connections work
  apt:
    name: ca-certificates
    state: present

- name: Add Nginx signing key
  apt_key:
    url: "{ nginx_repo_key_url }"
    state: present

- name: Add Nginx repository
  apt_repository:
    repo: "deb { nginx_repo_url } { ansible_distribution_release } nginx"
    state: present
    filename: nginx

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install specific version of Nginx
  apt:
    name: "nginx={ nginx_version }~{ ansible_distribution_release }"
    state: present

- name: Ensure Nginx service is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
