apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secretName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.app.environment }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
