apiVersion: v1
kind: Service
metadata:
  name: {{ include "myhelm.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.targetPort }}
      targetPort: {{ .Values.web.targetPort }}
  selector:
    app: {{ include "myhelm.name" . }}
