apiVersion: 1

datasources:
  - name: Alertmanager
    uid: alertmanager
    type: alertmanager
    url: http://localhost:9093
    access: proxy
    orgId: 1
    jsonData:
      # Valid options for implementation include mimir, cortex and prometheus
      implementation: [prometheus|cortex|mimir]
      # Whether or not Grafana should send alert instances to this Alertmanager
      handleGrafanaManagedAlerts: [false|true]

    editable: [true|false]
    # optionally
    basicAuth: true
    basicAuthUser: my_user
    secureJsonData:
      basicAuthPassword: test_password
